---
# tasks file for ansible-bmon

- block:
    - name: Install bmon packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
        install_recommends: no
      with_items:
        - "{{ bmon_packages }}"
        
  become: yes
  tags:
    - bmon
